set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets itimecode_clock]

set_property PACKAGE_PIN AE18 [get_ports {FTDI_BE[0]}]
set_property PACKAGE_PIN AF18 [get_ports {FTDI_BE[1]}]
set_property PACKAGE_PIN AE17 [get_ports {FTDI_BE[2]}]
set_property PACKAGE_PIN AF17 [get_ports {FTDI_BE[3]}]
set_property PACKAGE_PIN AE20 [get_ports {FTDI_ADBUS[0]}]
set_property PACKAGE_PIN AF20 [get_ports {FTDI_ADBUS[1]}]
set_property PACKAGE_PIN AD19 [get_ports {FTDI_ADBUS[2]}]
set_property PACKAGE_PIN AB20 [get_ports {FTDI_ADBUS[3]}]
set_property PACKAGE_PIN AD20 [get_ports {FTDI_ADBUS[4]}]
set_property PACKAGE_PIN AA19 [get_ports {FTDI_ADBUS[5]}]
set_property PACKAGE_PIN AB19 [get_ports {FTDI_ADBUS[6]}]
set_property PACKAGE_PIN AC19 [get_ports {FTDI_ADBUS[7]}]
set_property PACKAGE_PIN Y18 [get_ports {FTDI_ADBUS[8]}]
set_property PACKAGE_PIN V13 [get_ports {FTDI_ADBUS[9]}]
set_property PACKAGE_PIN AA18 [get_ports {FTDI_ADBUS[10]}]
set_property PACKAGE_PIN W19 [get_ports {FTDI_ADBUS[11]}]
set_property PACKAGE_PIN V18 [get_ports {FTDI_ADBUS[12]}]
set_property PACKAGE_PIN W18 [get_ports {FTDI_ADBUS[13]}]
set_property PACKAGE_PIN V17 [get_ports {FTDI_ADBUS[14]}]
set_property PACKAGE_PIN AE16 [get_ports {FTDI_ADBUS[15]}]
set_property PACKAGE_PIN W15 [get_ports {FTDI_ADBUS[16]}]
set_property PACKAGE_PIN AF19 [get_ports {FTDI_ADBUS[17]}]
set_property PACKAGE_PIN AD18 [get_ports {FTDI_ADBUS[18]}]
set_property PACKAGE_PIN AB17 [get_ports {FTDI_ADBUS[19]}]
set_property PACKAGE_PIN AC17 [get_ports {FTDI_ADBUS[20]}]
set_property PACKAGE_PIN AA17 [get_ports {FTDI_ADBUS[21]}]
set_property PACKAGE_PIN AB16 [get_ports {FTDI_ADBUS[22]}]
set_property PACKAGE_PIN AC16 [get_ports {FTDI_ADBUS[23]}]
set_property PACKAGE_PIN AA15 [get_ports {FTDI_ADBUS[24]}]
set_property PACKAGE_PIN AB15 [get_ports {FTDI_ADBUS[25]}]
set_property PACKAGE_PIN AD15 [get_ports {FTDI_ADBUS[26]}]
set_property PACKAGE_PIN AA14 [get_ports {FTDI_ADBUS[27]}]
set_property PACKAGE_PIN AB14 [get_ports {FTDI_ADBUS[28]}]
set_property PACKAGE_PIN Y15 [get_ports {FTDI_ADBUS[29]}]
set_property PACKAGE_PIN Y16 [get_ports {FTDI_ADBUS[30]}]
set_property PACKAGE_PIN W16 [get_ports {FTDI_ADBUS[31]}]
set_property PACKAGE_PIN AC14 [get_ports FTDI_OEN]
set_property PACKAGE_PIN AF14 [get_ports FTDI_RDN]
set_property PACKAGE_PIN AE15 [get_ports FTDI_RXFN]
set_property PACKAGE_PIN AD16 [get_ports FTDI_TXEN]
set_property PACKAGE_PIN AD14 [get_ports FTDI_TXN]
set_property PACKAGE_PIN AF15 [get_ports FTDI_SIWU]
#set_property PACKAGE_PIN AF19 [get_ports FTDI_CLK]
set_property PACKAGE_PIN AC18 [get_ports FTDI_CLK]


set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[27]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[28]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[29]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[30]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_ADBUS[31]}]

set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_BE[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_BE[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_BE[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FTDI_BE[3]}]

set_property IOSTANDARD LVCMOS18 [get_ports FTDI_OEN]
set_property IOSTANDARD LVCMOS18 [get_ports FTDI_RDN]
set_property IOSTANDARD LVCMOS18 [get_ports FTDI_RXFN]
set_property IOSTANDARD LVCMOS18 [get_ports FTDI_TXEN]
set_property IOSTANDARD LVCMOS18 [get_ports FTDI_TXN]
set_property IOSTANDARD LVCMOS18 [get_ports FTDI_SIWU]
set_property IOSTANDARD LVCMOS18 [get_ports FTDI_CLK]

#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets FTDI_CLK_IBUF]

create_clock -period 10.000 -name clk_ftdi -waveform {0.000 5.000} [get_ports FTDI_CLK]



set_property PACKAGE_PIN AE5 [get_ports CK_SPI_LE]
set_property PACKAGE_PIN AD5 [get_ports CK_SPI_CLK]
set_property PACKAGE_PIN AF4 [get_ports CK_SPI_MOSI]
set_property PACKAGE_PIN AF5 [get_ports CK_SPI_NSYNC]
set_property IOSTANDARD LVCMOS18 [get_ports CK_SPI_LE]
set_property IOSTANDARD LVCMOS18 [get_ports CK_SPI_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports CK_SPI_MOSI]
set_property IOSTANDARD LVCMOS18 [get_ports CK_SPI_NSYNC]

set_property PACKAGE_PIN AD21 [get_ports iic_scl]
set_property PACKAGE_PIN AE21 [get_ports iic_sda]
set_property IOSTANDARD LVCMOS18 [get_ports iic_scl]
set_property IOSTANDARD LVCMOS18 [get_ports iic_sda]


set_property PACKAGE_PIN B11 [get_ports PETIROC_A_CLK]
set_property PACKAGE_PIN D9 [get_ports PETIROC_A_MOSI]
set_property PACKAGE_PIN G12 [get_ports PETIROC_A_SLOAD]
set_property PACKAGE_PIN F12 [get_ports PETIROC_A_RESETB]
set_property PACKAGE_PIN A12 [get_ports PETIROC_A_SELECT]

set_property IOSTANDARD LVCMOS18 [get_ports PETIROC_A_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports PETIROC_A_MOSI]
set_property IOSTANDARD LVCMOS18 [get_ports PETIROC_A_SLOAD]
set_property IOSTANDARD LVCMOS18 [get_ports PETIROC_A_RESETB]
set_property IOSTANDARD LVCMOS18 [get_ports PETIROC_A_SELECT]


set_property PACKAGE_PIN F10 [get_ports A_ANALOG_DIN]
set_property PACKAGE_PIN H8 [get_ports A_ANALOG_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports A_ANALOG_DIN]
set_property IOSTANDARD LVCMOS18 [get_ports A_ANALOG_CLK]


set_property PACKAGE_PIN F19 [get_ports PETIROC_B_CLK]
set_property PACKAGE_PIN F15 [get_ports PETIROC_B_MOSI]
set_property PACKAGE_PIN F17 [get_ports PETIROC_B_SLOAD]
set_property PACKAGE_PIN D19 [get_ports PETIROC_B_RESETB]
set_property PACKAGE_PIN C16 [get_ports PETIROC_B_SELECT]

set_property IOSTANDARD LVCMOS18 [get_ports PETIROC_B_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports PETIROC_B_MOSI]
set_property IOSTANDARD LVCMOS18 [get_ports PETIROC_B_SLOAD]
set_property IOSTANDARD LVCMOS18 [get_ports PETIROC_B_RESETB]
set_property IOSTANDARD LVCMOS18 [get_ports PETIROC_B_SELECT]


set_property PACKAGE_PIN P23 [get_ports PETIROC_C_CLK]
set_property PACKAGE_PIN M19 [get_ports PETIROC_C_MOSI]
set_property PACKAGE_PIN N19 [get_ports PETIROC_C_SLOAD]
set_property PACKAGE_PIN N22 [get_ports PETIROC_C_RESETB]
set_property PACKAGE_PIN N18 [get_ports PETIROC_C_SELECT]

set_property IOSTANDARD LVCMOS18 [get_ports PETIROC_C_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports PETIROC_C_MOSI]
set_property IOSTANDARD LVCMOS18 [get_ports PETIROC_C_SLOAD]
set_property IOSTANDARD LVCMOS18 [get_ports PETIROC_C_RESETB]
set_property IOSTANDARD LVCMOS18 [get_ports PETIROC_C_SELECT]



set_property PACKAGE_PIN AB26 [get_ports PETIROC_D_CLK]
set_property PACKAGE_PIN AA23 [get_ports PETIROC_D_MOSI]
set_property PACKAGE_PIN W25 [get_ports PETIROC_D_SLOAD]
set_property PACKAGE_PIN AC23 [get_ports PETIROC_D_RESETB]
set_property PACKAGE_PIN AA24 [get_ports PETIROC_D_SELECT]

set_property IOSTANDARD LVCMOS18 [get_ports PETIROC_D_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports PETIROC_D_MOSI]
set_property IOSTANDARD LVCMOS18 [get_ports PETIROC_D_SLOAD]
set_property IOSTANDARD LVCMOS18 [get_ports PETIROC_D_RESETB]
set_property IOSTANDARD LVCMOS18 [get_ports PETIROC_D_SELECT]


set_property PACKAGE_PIN H24 [get_ports A_VAL_EVT_N]
set_property PACKAGE_PIN H23 [get_ports A_VAL_EVT_P]
set_property PACKAGE_PIN E22 [get_ports B_VAL_EVT_N]
set_property PACKAGE_PIN E21 [get_ports B_VAL_EVT_P]
set_property PACKAGE_PIN C26 [get_ports C_VAL_EVT_N]
set_property PACKAGE_PIN D26 [get_ports C_VAL_EVT_P]
set_property PACKAGE_PIN G26 [get_ports D_VAL_EVT_N]
set_property PACKAGE_PIN G25 [get_ports D_VAL_EVT_P]


set_property PACKAGE_PIN H22 [get_ports A_RAZ_CHN_N]
set_property PACKAGE_PIN J21 [get_ports A_RAZ_CHN_P]
set_property PACKAGE_PIN F23 [get_ports B_RAZ_CHN_N]
set_property PACKAGE_PIN G22 [get_ports B_RAZ_CHN_P]
set_property PACKAGE_PIN J25 [get_ports C_RAZ_CHN_N]
set_property PACKAGE_PIN J24 [get_ports C_RAZ_CHN_P]
set_property PACKAGE_PIN E26 [get_ports D_RAZ_CHN_N]
set_property PACKAGE_PIN F25 [get_ports D_RAZ_CHN_P]



set_property PACKAGE_PIN P19 [get_ports C_TRIG_EXT]
set_property PACKAGE_PIN K17 [get_ports B_TRIG_EXT]
set_property PACKAGE_PIN H13 [get_ports A_TRIG_EXT]
set_property PACKAGE_PIN AF25 [get_ports D_TRIG_EXT]

set_property IOSTANDARD LVCMOS18 [get_ports A_TRIG_EXT]
set_property IOSTANDARD LVCMOS18 [get_ports B_TRIG_EXT]
set_property IOSTANDARD LVCMOS18 [get_ports C_TRIG_EXT]
set_property IOSTANDARD LVCMOS18 [get_ports D_TRIG_EXT]





set_property IOSTANDARD LVDS_25 [get_ports A_VAL_EVT_P]
set_property IOSTANDARD LVDS_25 [get_ports A_VAL_EVT_N]
set_property IOSTANDARD LVDS_25 [get_ports B_VAL_EVT_P]
set_property IOSTANDARD LVDS_25 [get_ports B_VAL_EVT_N]
set_property IOSTANDARD LVDS_25 [get_ports C_VAL_EVT_P]
set_property IOSTANDARD LVDS_25 [get_ports C_VAL_EVT_N]

set_property IOSTANDARD LVDS_25 [get_ports D_VAL_EVT_P]
set_property IOSTANDARD LVDS_25 [get_ports D_VAL_EVT_N]
#set_property IOSTANDARD LVDS_25 [get_ports D_VAL_EVT_P]
#set_property IOSTANDARD LVDS_25 [get_ports D_VAL_EVT_N]


set_property PACKAGE_PIN J10 [get_ports PETIROC_A_RSTB]
set_property PACKAGE_PIN H19 [get_ports PETIROC_B_RSTB]
set_property PACKAGE_PIN M25 [get_ports PETIROC_C_RSTB]
set_property PACKAGE_PIN AC24 [get_ports PETIROC_D_RSTB]

set_property IOSTANDARD LVCMOS18 [get_ports PETIROC_A_RSTB]
set_property IOSTANDARD LVCMOS18 [get_ports PETIROC_B_RSTB]
set_property IOSTANDARD LVCMOS18 [get_ports PETIROC_C_RSTB]
set_property IOSTANDARD LVCMOS18 [get_ports PETIROC_D_RSTB]

set_property IOSTANDARD LVDS_25 [get_ports A_RAZ_CHN_P]
set_property IOSTANDARD LVDS_25 [get_ports A_RAZ_CHN_N]
set_property IOSTANDARD LVDS_25 [get_ports B_RAZ_CHN_P]
set_property IOSTANDARD LVDS_25 [get_ports B_RAZ_CHN_N]
set_property IOSTANDARD LVDS_25 [get_ports C_RAZ_CHN_P]
set_property IOSTANDARD LVDS_25 [get_ports C_RAZ_CHN_N]
#set_property IOSTANDARD LVDS_25 [get_ports D_RAZ_CHN_P]
#set_property IOSTANDARD LVDS_25 [get_ports D_RAZ_CHN_N]

set_property IOSTANDARD LVDS_25 [get_ports D_RAZ_CHN_P]
set_property IOSTANDARD LVDS_25 [get_ports D_RAZ_CHN_N]



set_property PACKAGE_PIN A14 [get_ports A_START_CONV]
set_property PACKAGE_PIN D18 [get_ports B_START_CONV]
set_property PACKAGE_PIN M22 [get_ports C_START_CONV]
set_property PACKAGE_PIN Y26 [get_ports D_START_CONV]


set_property PACKAGE_PIN B14 [get_ports A_STARTB_ADC_EXT]
set_property PACKAGE_PIN D20 [get_ports B_STARTB_ADC_EXT]
set_property PACKAGE_PIN P21 [get_ports C_STARTB_ADC_EXT]
set_property PACKAGE_PIN Y25 [get_ports D_STARTB_ADC_EXT]

set_property PACKAGE_PIN D11 [get_ports A_HOLD_EXT]
set_property PACKAGE_PIN E20 [get_ports B_HOLD_EXT]
set_property PACKAGE_PIN P25 [get_ports C_HOLD_EXT]
set_property PACKAGE_PIN AD26 [get_ports D_HOLD_EXT]


set_property IOSTANDARD LVCMOS18 [get_ports A_START_CONV]
set_property IOSTANDARD LVCMOS18 [get_ports B_START_CONV]
set_property IOSTANDARD LVCMOS18 [get_ports C_START_CONV]
set_property IOSTANDARD LVCMOS18 [get_ports D_START_CONV]

set_property IOSTANDARD LVCMOS18 [get_ports A_STARTB_ADC_EXT]
set_property IOSTANDARD LVCMOS18 [get_ports B_STARTB_ADC_EXT]
set_property IOSTANDARD LVCMOS18 [get_ports C_STARTB_ADC_EXT]
set_property IOSTANDARD LVCMOS18 [get_ports D_STARTB_ADC_EXT]

set_property IOSTANDARD LVCMOS18 [get_ports A_HOLD_EXT]
set_property IOSTANDARD LVCMOS18 [get_ports B_HOLD_EXT]
set_property IOSTANDARD LVCMOS18 [get_ports C_HOLD_EXT]
set_property IOSTANDARD LVCMOS18 [get_ports D_HOLD_EXT]


set_property PACKAGE_PIN J23 [get_ports D_TRASMIT_ON]
set_property PACKAGE_PIN E25 [get_ports C_TRASMIT_ON]
set_property PACKAGE_PIN B20 [get_ports A_TRASMIT_ON]

set_property PACKAGE_PIN J26 [get_ports D_LVDS_DOUT_P]
set_property PACKAGE_PIN G24 [get_ports C_LVDS_DOUT_P]
set_property PACKAGE_PIN D21 [get_ports A_LVDS_DOUT_P]

set_property PACKAGE_PIN AC9 [get_ports D_LVDS_DCLK_P]

set_property IOSTANDARD LVCMOS25 [get_ports D_TRASMIT_ON]
set_property IOSTANDARD LVCMOS25 [get_ports C_TRASMIT_ON]
set_property IOSTANDARD LVCMOS25 [get_ports A_TRASMIT_ON]

set_property IOSTANDARD LVDS_25 [get_ports C_LVDS_DOUT_P]
set_property IOSTANDARD LVDS_25 [get_ports C_LVDS_DOUT_N]

set_property IOSTANDARD LVDS_25 [get_ports D_LVDS_DOUT_P]
set_property IOSTANDARD LVDS_25 [get_ports D_LVDS_DOUT_N]

set_property IOSTANDARD LVDS_25 [get_ports A_LVDS_DOUT_P]
set_property IOSTANDARD LVDS_25 [get_ports A_LVDS_DOUT_N]


set_property IOSTANDARD LVDS [get_ports D_LVDS_DCLK_P]
set_property IOSTANDARD LVDS [get_ports D_LVDS_DCLK_N]


set_property PACKAGE_PIN C12 [get_ports {A_TRG[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[0]}]
set_property PACKAGE_PIN G14 [get_ports {A_TRG[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[1]}]
set_property PACKAGE_PIN H14 [get_ports {A_TRG[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[2]}]
set_property PACKAGE_PIN J13 [get_ports {A_TRG[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[3]}]
set_property PACKAGE_PIN F13 [get_ports {A_TRG[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[4]}]
set_property PACKAGE_PIN E11 [get_ports {A_TRG[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[5]}]
set_property PACKAGE_PIN D10 [get_ports {A_TRG[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[6]}]
set_property PACKAGE_PIN E12 [get_ports {A_TRG[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[7]}]
set_property PACKAGE_PIN H12 [get_ports {A_TRG[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[8]}]
set_property PACKAGE_PIN A15 [get_ports {A_TRG[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[9]}]
set_property PACKAGE_PIN F8 [get_ports {A_TRG[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[10]}]
set_property PACKAGE_PIN D8 [get_ports {A_TRG[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[11]}]
set_property PACKAGE_PIN A10 [get_ports {A_TRG[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[12]}]
set_property PACKAGE_PIN B9 [get_ports {A_TRG[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[13]}]
set_property PACKAGE_PIN F9 [get_ports {A_TRG[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[14]}]
set_property PACKAGE_PIN H11 [get_ports {A_TRG[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[15]}]
set_property PACKAGE_PIN A13 [get_ports {A_TRG[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[16]}]
set_property PACKAGE_PIN B10 [get_ports {A_TRG[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[17]}]
set_property PACKAGE_PIN A9 [get_ports {A_TRG[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[18]}]
set_property PACKAGE_PIN A8 [get_ports {A_TRG[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[19]}]
set_property PACKAGE_PIN J14 [get_ports {A_TRG[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[20]}]
set_property PACKAGE_PIN B12 [get_ports {A_TRG[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[21]}]
set_property PACKAGE_PIN C11 [get_ports {A_TRG[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[22]}]
set_property PACKAGE_PIN E13 [get_ports {A_TRG[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[23]}]
set_property PACKAGE_PIN B15 [get_ports {A_TRG[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[24]}]
set_property PACKAGE_PIN G11 [get_ports {A_TRG[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[25]}]
set_property PACKAGE_PIN F14 [get_ports {A_TRG[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[26]}]
set_property PACKAGE_PIN E10 [get_ports {A_TRG[27]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[27]}]
set_property PACKAGE_PIN J11 [get_ports {A_TRG[28]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[28]}]
set_property PACKAGE_PIN G10 [get_ports {A_TRG[29]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[29]}]
set_property PACKAGE_PIN G9 [get_ports {A_TRG[30]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[30]}]
set_property PACKAGE_PIN H9 [get_ports {A_TRG[31]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A_TRG[31]}]








set_property PACKAGE_PIN V11 [get_ports LEMO0]
set_property IOSTANDARD LVCMOS18 [get_ports LEMO0]
set_property PACKAGE_PIN W11 [get_ports LEMO1]
set_property IOSTANDARD LVCMOS18 [get_ports LEMO1]
set_property PACKAGE_PIN Y13 [get_ports LEMO2]
set_property IOSTANDARD LVCMOS18 [get_ports LEMO2]
set_property PACKAGE_PIN AA13 [get_ports LEMO3]
set_property IOSTANDARD LVCMOS18 [get_ports LEMO3]
set_property PACKAGE_PIN AC12 [get_ports LEMO4]
set_property IOSTANDARD LVCMOS18 [get_ports LEMO4]
set_property PACKAGE_PIN AB12 [get_ports LEMO5]
set_property IOSTANDARD LVCMOS18 [get_ports LEMO5]
set_property PACKAGE_PIN AA12 [get_ports LEMO6]
set_property IOSTANDARD LVCMOS18 [get_ports LEMO6]
set_property PACKAGE_PIN Y12 [get_ports LEMO7]
set_property IOSTANDARD LVCMOS18 [get_ports LEMO7]

set_property PACKAGE_PIN V12 [get_ports LEMO01_dir]
set_property IOSTANDARD LVCMOS18 [get_ports LEMO01_dir]
set_property PACKAGE_PIN AD13 [get_ports LEMO23_dir]
set_property IOSTANDARD LVCMOS18 [get_ports LEMO23_dir]
set_property PACKAGE_PIN AC13 [get_ports LEMO45_dir]
set_property IOSTANDARD LVCMOS18 [get_ports LEMO45_dir]
set_property PACKAGE_PIN AE10 [get_ports LEMO67_dir]
set_property IOSTANDARD LVCMOS18 [get_ports LEMO67_dir]


set_property PACKAGE_PIN AE7 [get_ports CLK_40_P]
set_property IOSTANDARD LVDS [get_ports CLK_40_P]



set_property PACKAGE_PIN B24 [get_ports FLASH_SPI_DOUT]
set_property IOSTANDARD LVCMOS25 [get_ports FLASH_SPI_DOUT]
set_property PACKAGE_PIN A25 [get_ports FLASH_SPI_DIN]
set_property IOSTANDARD LVCMOS25 [get_ports FLASH_SPI_DIN]
set_property PACKAGE_PIN C23 [get_ports FLASH_SPI_CS]
set_property IOSTANDARD LVCMOS25 [get_ports FLASH_SPI_CS]

create_clock -period 6.250 -name D_LVDS_DCLK -waveform {0.000 5.000} [get_ports D_LVDS_DCLK_P]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets timecode_clock]



set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 12 [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR NO [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CFGBVS GND [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design]

set_property PACKAGE_PIN K15 [get_ports {B_TRG[10]}]
set_property PACKAGE_PIN B16 [get_ports {B_TRG[2]}]
set_property PACKAGE_PIN A18 [get_ports {B_TRG[7]}]
set_property PACKAGE_PIN A19 [get_ports {B_TRG[15]}]
set_property PACKAGE_PIN B17 [get_ports {B_TRG[3]}]
set_property PACKAGE_PIN A17 [get_ports {B_TRG[13]}]
set_property PACKAGE_PIN C19 [get_ports {B_TRG[6]}]
set_property PACKAGE_PIN B19 [get_ports {B_TRG[26]}]
set_property PACKAGE_PIN C17 [get_ports {B_TRG[14]}]
set_property PACKAGE_PIN C18 [get_ports {B_TRG[4]}]
set_property PACKAGE_PIN D16 [get_ports {B_TRG[21]}]
set_property PACKAGE_PIN H16 [get_ports {B_TRG[22]}]
set_property PACKAGE_PIN G16 [get_ports {B_TRG[1]}]
set_property PACKAGE_PIN G15 [get_ports {B_TRG[23]}]
set_property PACKAGE_PIN J16 [get_ports {B_TRG[0]}]
set_property PACKAGE_PIN E15 [get_ports {B_TRG[20]}]
set_property PACKAGE_PIN E16 [get_ports {B_TRG[31]}]
set_property PACKAGE_PIN G17 [get_ports {B_TRG[5]}]
set_property PACKAGE_PIN F18 [get_ports {B_TRG[16]}]
set_property PACKAGE_PIN E17 [get_ports {B_TRG[25]}]
set_property PACKAGE_PIN E18 [get_ports {B_TRG[12]}]
set_property PACKAGE_PIN G19 [get_ports {B_TRG[17]}]
set_property PACKAGE_PIN F20 [get_ports {B_TRG[27]}]
set_property PACKAGE_PIN G20 [get_ports {B_TRG[24]}]
set_property PACKAGE_PIN J18 [get_ports {B_TRG[8]}]
set_property PACKAGE_PIN J19 [get_ports {B_TRG[29]}]
set_property PACKAGE_PIN K16 [get_ports {B_TRG[11]}]
set_property PACKAGE_PIN M17 [get_ports {B_TRG[28]}]
set_property PACKAGE_PIN L18 [get_ports {B_TRG[18]}]
set_property PACKAGE_PIN K18 [get_ports {B_TRG[19]}]
set_property PACKAGE_PIN M16 [get_ports {B_TRG[9]}]
set_property PACKAGE_PIN H18 [get_ports {B_TRG[30]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[31]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[30]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[29]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[28]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[27]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TRG[0]}]
set_property PACKAGE_PIN D23 [get_ports B_LVDS_DOUT_P]
set_property IOSTANDARD LVDS_25 [get_ports B_LVDS_DOUT_P]
set_property PACKAGE_PIN G21 [get_ports B_TRASMIT_ON]
set_property IOSTANDARD LVCMOS25 [get_ports B_TRASMIT_ON]

#set_property MARK_DEBUG true [get_nets USBInterface/Inst_ft600_fifo245_core/FTDI_OEN]
#set_property MARK_DEBUG true [get_nets USBInterface/Inst_ft600_fifo245_core/FTDI_RDN]
#set_property MARK_DEBUG true [get_nets USBInterface/Inst_ft600_fifo245_core/FTDI_RXFN_IBUF]
#set_property MARK_DEBUG true [get_nets USBInterface/Inst_ft600_fifo245_core/FTDI_TXEN_IBUF]
#set_property MARK_DEBUG true [get_nets USBInterface/Inst_ft600_fifo245_core/FTDI_TXN_OBUF]
#set_property MARK_DEBUG true [get_nets USBInterface/Inst_ft600_fifo245_core/VetoTX]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[0]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[10]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[11]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[12]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[13]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[14]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[15]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[16]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[17]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[18]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[19]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[1]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[20]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[21]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[22]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[23]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[24]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[25]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[26]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[27]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[28]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[29]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[2]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[30]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[31]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[3]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[4]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[5]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[6]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[7]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[8]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/addr[9]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[0]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[10]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[11]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[12]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[13]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[14]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[15]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[16]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[17]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[18]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[19]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[1]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[20]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[21]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[22]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[23]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[24]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[25]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[26]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[27]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[28]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[29]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[2]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[30]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[31]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[3]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[4]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[5]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[6]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[7]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[8]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/burst_paylan[9]}]
#set_property MARK_DEBUG true [get_nets USBInterface/Inst_ft600_fifo245_core/data_valid]
#set_property MARK_DEBUG true [get_nets USBInterface/Inst_ft600_fifo245_core/direction]
#set_property MARK_DEBUG true [get_nets USBInterface/Inst_ft600_fifo245_core/fifo_reset]
#set_property MARK_DEBUG true [get_nets USBInterface/Inst_ft600_fifo245_core/iFTDI_TXN]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[0]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[10]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[11]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[12]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[13]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[14]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[15]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[16]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[17]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[18]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[19]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[1]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[20]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[21]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[22]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[23]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[24]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[25]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[26]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[27]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[28]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[29]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[2]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[30]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[31]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[3]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[4]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[5]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[6]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[7]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[8]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[9]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[0]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[10]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[11]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[12]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[13]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[14]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[15]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[16]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[17]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[18]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[19]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[1]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[20]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[21]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[22]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[23]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[24]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[25]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[26]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[27]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[28]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[29]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[2]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[30]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[31]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[3]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[4]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[5]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[6]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[7]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[8]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[9]}]
#set_property MARK_DEBUG true [get_nets USBInterface/Inst_ft600_fifo245_core/int_FTDI_RXFN]
#set_property MARK_DEBUG true [get_nets USBInterface/Inst_ft600_fifo245_core/int_FTDI_TXEN]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[0]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[10]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[11]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[12]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[13]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[14]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[15]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[16]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[17]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[18]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[19]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[1]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[20]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[21]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[22]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[23]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[24]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[25]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[26]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[27]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[28]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[29]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[2]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[30]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[31]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[3]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[4]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[5]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[6]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[7]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[8]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/int_addr[9]}]
#set_property MARK_DEBUG true [get_nets USBInterface/Inst_ft600_fifo245_core/int_reset]
#set_property MARK_DEBUG true [get_nets USBInterface/Inst_ft600_fifo245_core/int_wr]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[0]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[10]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[11]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[12]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[13]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[14]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[15]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[16]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[17]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[18]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[19]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[1]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[20]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[21]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[22]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[23]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[24]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[25]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[26]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[27]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[28]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[29]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[2]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[30]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[31]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[3]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[4]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[5]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[6]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[7]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[8]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/paylan[9]}]
#set_property MARK_DEBUG true [get_nets USBInterface/Inst_ft600_fifo245_core/prog_full]
#set_property MARK_DEBUG true [get_nets USBInterface/Inst_ft600_fifo245_core/push_address_in_fifo_for_burst]
#set_property MARK_DEBUG true [get_nets USBInterface/Inst_ft600_fifo245_core/req_read_data]
#set_property MARK_DEBUG true [get_nets USBInterface/Inst_ft600_fifo245_core/send_shit]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/state_interface[0]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/state_interface[1]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/state_interface[2]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/state_interface[3]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/state_interface[4]}]
#set_property MARK_DEBUG true [get_nets USBInterface/Inst_ft600_fifo245_core/streaming_mode]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[16]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[17]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[18]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[19]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[20]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[21]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[22]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[23]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[24]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[25]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[26]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[27]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[28]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[29]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[30]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[31]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[32]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[33]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[34]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[35]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[36]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[37]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[38]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[39]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[40]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[41]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[42]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[43]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[44]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[45]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[46]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/timeout_counter[47]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/use_alter_data[0]}]
#set_property MARK_DEBUG true [get_nets {USBInterface/Inst_ft600_fifo245_core/use_alter_data[1]}]
#set_property MARK_DEBUG true [get_nets USBInterface/Inst_ft600_fifo245_core/valid]
#create_debug_core u_ila_0 ila
#set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
#set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
#set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
#set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
#set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
#set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
#set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
#set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
#set_property port_width 1 [get_debug_ports u_ila_0/clk]
#connect_debug_port u_ila_0/clk [get_nets [list FTDI_CLK_IBUF_BUFG]]
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
#set_property port_width 32 [get_debug_ports u_ila_0/probe0]
#connect_debug_port u_ila_0/probe0 [get_nets [list {USBInterface/Inst_ft600_fifo245_core/timeout_counter[16]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[17]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[18]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[19]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[20]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[21]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[22]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[23]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[24]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[25]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[26]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[27]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[28]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[29]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[30]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[31]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[32]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[33]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[34]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[35]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[36]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[37]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[38]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[39]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[40]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[41]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[42]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[43]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[44]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[45]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[46]} {USBInterface/Inst_ft600_fifo245_core/timeout_counter[47]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
#set_property port_width 2 [get_debug_ports u_ila_0/probe1]
#connect_debug_port u_ila_0/probe1 [get_nets [list {USBInterface/Inst_ft600_fifo245_core/use_alter_data[1]} {USBInterface/Inst_ft600_fifo245_core/use_alter_data[0]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
#set_property port_width 5 [get_debug_ports u_ila_0/probe2]
#connect_debug_port u_ila_0/probe2 [get_nets [list {USBInterface/Inst_ft600_fifo245_core/state_interface[0]} {USBInterface/Inst_ft600_fifo245_core/state_interface[1]} {USBInterface/Inst_ft600_fifo245_core/state_interface[2]} {USBInterface/Inst_ft600_fifo245_core/state_interface[3]} {USBInterface/Inst_ft600_fifo245_core/state_interface[4]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
#set_property port_width 32 [get_debug_ports u_ila_0/probe3]
#connect_debug_port u_ila_0/probe3 [get_nets [list {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[0]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[1]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[2]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[3]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[4]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[5]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[6]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[7]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[8]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[9]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[10]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[11]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[12]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[13]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[14]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[15]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[16]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[17]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[18]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[19]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[20]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[21]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[22]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[23]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[24]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[25]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[26]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[27]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[28]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[29]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[30]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DIN[31]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
#set_property port_width 32 [get_debug_ports u_ila_0/probe4]
#connect_debug_port u_ila_0/probe4 [get_nets [list {USBInterface/Inst_ft600_fifo245_core/addr[0]} {USBInterface/Inst_ft600_fifo245_core/addr[1]} {USBInterface/Inst_ft600_fifo245_core/addr[2]} {USBInterface/Inst_ft600_fifo245_core/addr[3]} {USBInterface/Inst_ft600_fifo245_core/addr[4]} {USBInterface/Inst_ft600_fifo245_core/addr[5]} {USBInterface/Inst_ft600_fifo245_core/addr[6]} {USBInterface/Inst_ft600_fifo245_core/addr[7]} {USBInterface/Inst_ft600_fifo245_core/addr[8]} {USBInterface/Inst_ft600_fifo245_core/addr[9]} {USBInterface/Inst_ft600_fifo245_core/addr[10]} {USBInterface/Inst_ft600_fifo245_core/addr[11]} {USBInterface/Inst_ft600_fifo245_core/addr[12]} {USBInterface/Inst_ft600_fifo245_core/addr[13]} {USBInterface/Inst_ft600_fifo245_core/addr[14]} {USBInterface/Inst_ft600_fifo245_core/addr[15]} {USBInterface/Inst_ft600_fifo245_core/addr[16]} {USBInterface/Inst_ft600_fifo245_core/addr[17]} {USBInterface/Inst_ft600_fifo245_core/addr[18]} {USBInterface/Inst_ft600_fifo245_core/addr[19]} {USBInterface/Inst_ft600_fifo245_core/addr[20]} {USBInterface/Inst_ft600_fifo245_core/addr[21]} {USBInterface/Inst_ft600_fifo245_core/addr[22]} {USBInterface/Inst_ft600_fifo245_core/addr[23]} {USBInterface/Inst_ft600_fifo245_core/addr[24]} {USBInterface/Inst_ft600_fifo245_core/addr[25]} {USBInterface/Inst_ft600_fifo245_core/addr[26]} {USBInterface/Inst_ft600_fifo245_core/addr[27]} {USBInterface/Inst_ft600_fifo245_core/addr[28]} {USBInterface/Inst_ft600_fifo245_core/addr[29]} {USBInterface/Inst_ft600_fifo245_core/addr[30]} {USBInterface/Inst_ft600_fifo245_core/addr[31]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
#set_property port_width 32 [get_debug_ports u_ila_0/probe5]
#connect_debug_port u_ila_0/probe5 [get_nets [list {USBInterface/Inst_ft600_fifo245_core/burst_paylan[0]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[1]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[2]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[3]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[4]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[5]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[6]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[7]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[8]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[9]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[10]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[11]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[12]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[13]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[14]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[15]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[16]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[17]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[18]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[19]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[20]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[21]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[22]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[23]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[24]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[25]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[26]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[27]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[28]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[29]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[30]} {USBInterface/Inst_ft600_fifo245_core/burst_paylan[31]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
#set_property port_width 32 [get_debug_ports u_ila_0/probe6]
#connect_debug_port u_ila_0/probe6 [get_nets [list {USBInterface/Inst_ft600_fifo245_core/paylan[0]} {USBInterface/Inst_ft600_fifo245_core/paylan[1]} {USBInterface/Inst_ft600_fifo245_core/paylan[2]} {USBInterface/Inst_ft600_fifo245_core/paylan[3]} {USBInterface/Inst_ft600_fifo245_core/paylan[4]} {USBInterface/Inst_ft600_fifo245_core/paylan[5]} {USBInterface/Inst_ft600_fifo245_core/paylan[6]} {USBInterface/Inst_ft600_fifo245_core/paylan[7]} {USBInterface/Inst_ft600_fifo245_core/paylan[8]} {USBInterface/Inst_ft600_fifo245_core/paylan[9]} {USBInterface/Inst_ft600_fifo245_core/paylan[10]} {USBInterface/Inst_ft600_fifo245_core/paylan[11]} {USBInterface/Inst_ft600_fifo245_core/paylan[12]} {USBInterface/Inst_ft600_fifo245_core/paylan[13]} {USBInterface/Inst_ft600_fifo245_core/paylan[14]} {USBInterface/Inst_ft600_fifo245_core/paylan[15]} {USBInterface/Inst_ft600_fifo245_core/paylan[16]} {USBInterface/Inst_ft600_fifo245_core/paylan[17]} {USBInterface/Inst_ft600_fifo245_core/paylan[18]} {USBInterface/Inst_ft600_fifo245_core/paylan[19]} {USBInterface/Inst_ft600_fifo245_core/paylan[20]} {USBInterface/Inst_ft600_fifo245_core/paylan[21]} {USBInterface/Inst_ft600_fifo245_core/paylan[22]} {USBInterface/Inst_ft600_fifo245_core/paylan[23]} {USBInterface/Inst_ft600_fifo245_core/paylan[24]} {USBInterface/Inst_ft600_fifo245_core/paylan[25]} {USBInterface/Inst_ft600_fifo245_core/paylan[26]} {USBInterface/Inst_ft600_fifo245_core/paylan[27]} {USBInterface/Inst_ft600_fifo245_core/paylan[28]} {USBInterface/Inst_ft600_fifo245_core/paylan[29]} {USBInterface/Inst_ft600_fifo245_core/paylan[30]} {USBInterface/Inst_ft600_fifo245_core/paylan[31]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
#set_property port_width 32 [get_debug_ports u_ila_0/probe7]
#connect_debug_port u_ila_0/probe7 [get_nets [list {USBInterface/Inst_ft600_fifo245_core/int_addr[0]} {USBInterface/Inst_ft600_fifo245_core/int_addr[1]} {USBInterface/Inst_ft600_fifo245_core/int_addr[2]} {USBInterface/Inst_ft600_fifo245_core/int_addr[3]} {USBInterface/Inst_ft600_fifo245_core/int_addr[4]} {USBInterface/Inst_ft600_fifo245_core/int_addr[5]} {USBInterface/Inst_ft600_fifo245_core/int_addr[6]} {USBInterface/Inst_ft600_fifo245_core/int_addr[7]} {USBInterface/Inst_ft600_fifo245_core/int_addr[8]} {USBInterface/Inst_ft600_fifo245_core/int_addr[9]} {USBInterface/Inst_ft600_fifo245_core/int_addr[10]} {USBInterface/Inst_ft600_fifo245_core/int_addr[11]} {USBInterface/Inst_ft600_fifo245_core/int_addr[12]} {USBInterface/Inst_ft600_fifo245_core/int_addr[13]} {USBInterface/Inst_ft600_fifo245_core/int_addr[14]} {USBInterface/Inst_ft600_fifo245_core/int_addr[15]} {USBInterface/Inst_ft600_fifo245_core/int_addr[16]} {USBInterface/Inst_ft600_fifo245_core/int_addr[17]} {USBInterface/Inst_ft600_fifo245_core/int_addr[18]} {USBInterface/Inst_ft600_fifo245_core/int_addr[19]} {USBInterface/Inst_ft600_fifo245_core/int_addr[20]} {USBInterface/Inst_ft600_fifo245_core/int_addr[21]} {USBInterface/Inst_ft600_fifo245_core/int_addr[22]} {USBInterface/Inst_ft600_fifo245_core/int_addr[23]} {USBInterface/Inst_ft600_fifo245_core/int_addr[24]} {USBInterface/Inst_ft600_fifo245_core/int_addr[25]} {USBInterface/Inst_ft600_fifo245_core/int_addr[26]} {USBInterface/Inst_ft600_fifo245_core/int_addr[27]} {USBInterface/Inst_ft600_fifo245_core/int_addr[28]} {USBInterface/Inst_ft600_fifo245_core/int_addr[29]} {USBInterface/Inst_ft600_fifo245_core/int_addr[30]} {USBInterface/Inst_ft600_fifo245_core/int_addr[31]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
#set_property port_width 32 [get_debug_ports u_ila_0/probe8]
#connect_debug_port u_ila_0/probe8 [get_nets [list {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[0]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[1]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[2]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[3]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[4]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[5]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[6]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[7]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[8]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[9]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[10]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[11]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[12]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[13]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[14]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[15]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[16]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[17]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[18]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[19]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[20]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[21]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[22]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[23]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[24]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[25]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[26]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[27]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[28]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[29]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[30]} {USBInterface/Inst_ft600_fifo245_core/int_FTDI_DOUT[31]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
#set_property port_width 1 [get_debug_ports u_ila_0/probe9]
#connect_debug_port u_ila_0/probe9 [get_nets [list USBInterface/Inst_ft600_fifo245_core/data_valid]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
#set_property port_width 1 [get_debug_ports u_ila_0/probe10]
#connect_debug_port u_ila_0/probe10 [get_nets [list USBInterface/Inst_ft600_fifo245_core/direction]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
#set_property port_width 1 [get_debug_ports u_ila_0/probe11]
#connect_debug_port u_ila_0/probe11 [get_nets [list USBInterface/Inst_ft600_fifo245_core/fifo_reset]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
#set_property port_width 1 [get_debug_ports u_ila_0/probe12]
#connect_debug_port u_ila_0/probe12 [get_nets [list USBInterface/Inst_ft600_fifo245_core/FTDI_OEN]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
#set_property port_width 1 [get_debug_ports u_ila_0/probe13]
#connect_debug_port u_ila_0/probe13 [get_nets [list USBInterface/Inst_ft600_fifo245_core/FTDI_RDN]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
#set_property port_width 1 [get_debug_ports u_ila_0/probe14]
#connect_debug_port u_ila_0/probe14 [get_nets [list USBInterface/Inst_ft600_fifo245_core/FTDI_RXFN_IBUF]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
#set_property port_width 1 [get_debug_ports u_ila_0/probe15]
#connect_debug_port u_ila_0/probe15 [get_nets [list USBInterface/Inst_ft600_fifo245_core/FTDI_TXEN_IBUF]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
#set_property port_width 1 [get_debug_ports u_ila_0/probe16]
#connect_debug_port u_ila_0/probe16 [get_nets [list USBInterface/Inst_ft600_fifo245_core/FTDI_TXN_OBUF]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
#set_property port_width 1 [get_debug_ports u_ila_0/probe17]
#connect_debug_port u_ila_0/probe17 [get_nets [list USBInterface/Inst_ft600_fifo245_core/iFTDI_TXN]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
#set_property port_width 1 [get_debug_ports u_ila_0/probe18]
#connect_debug_port u_ila_0/probe18 [get_nets [list USBInterface/Inst_ft600_fifo245_core/int_FTDI_RXFN]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
#set_property port_width 1 [get_debug_ports u_ila_0/probe19]
#connect_debug_port u_ila_0/probe19 [get_nets [list USBInterface/Inst_ft600_fifo245_core/int_FTDI_TXEN]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
#set_property port_width 1 [get_debug_ports u_ila_0/probe20]
#connect_debug_port u_ila_0/probe20 [get_nets [list USBInterface/Inst_ft600_fifo245_core/int_reset]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
#set_property port_width 1 [get_debug_ports u_ila_0/probe21]
#connect_debug_port u_ila_0/probe21 [get_nets [list USBInterface/Inst_ft600_fifo245_core/int_wr]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
#set_property port_width 1 [get_debug_ports u_ila_0/probe22]
#connect_debug_port u_ila_0/probe22 [get_nets [list USBInterface/Inst_ft600_fifo245_core/prog_full]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
#set_property port_width 1 [get_debug_ports u_ila_0/probe23]
#connect_debug_port u_ila_0/probe23 [get_nets [list USBInterface/Inst_ft600_fifo245_core/push_address_in_fifo_for_burst]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
#set_property port_width 1 [get_debug_ports u_ila_0/probe24]
#connect_debug_port u_ila_0/probe24 [get_nets [list USBInterface/Inst_ft600_fifo245_core/req_read_data]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
#set_property port_width 1 [get_debug_ports u_ila_0/probe25]
#connect_debug_port u_ila_0/probe25 [get_nets [list USBInterface/Inst_ft600_fifo245_core/send_shit]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
#set_property port_width 1 [get_debug_ports u_ila_0/probe26]
#connect_debug_port u_ila_0/probe26 [get_nets [list USBInterface/Inst_ft600_fifo245_core/streaming_mode]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
#set_property port_width 1 [get_debug_ports u_ila_0/probe27]
#connect_debug_port u_ila_0/probe27 [get_nets [list USBInterface/Inst_ft600_fifo245_core/valid]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
#set_property port_width 1 [get_debug_ports u_ila_0/probe28]
#connect_debug_port u_ila_0/probe28 [get_nets [list USBInterface/Inst_ft600_fifo245_core/VetoTX]]
#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets FTDI_CLK_IBUF_BUFG]



create_clock -period 25.000 -name CLK_40_P -waveform {0.000 6.250} [get_ports CLK_40_P]
set_clock_groups -asynchronous -group [get_clocks CLK_40_P] -group [get_clocks D_LVDS_DCLK]

create_clock -period 2.283 -name ADC_1_CLK_A_P -waveform {0.000 1.142} [get_ports ADC_1_CLK_A_P]
set_property PACKAGE_PIN AE11 [get_ports SMADC_1_CLK]
set_property PACKAGE_PIN AD10 [get_ports SMADC_1_MOSI]
set_property PACKAGE_PIN AE13 [get_ports SMADC_1_RESET]
set_property PACKAGE_PIN AD11 [get_ports SMADC_1_CSA]
set_property PACKAGE_PIN AF13 [get_ports SMADC_1_PD]

set_property IOSTANDARD LVCMOS18 [get_ports SMADC_1_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports SMADC_1_MOSI]
set_property IOSTANDARD LVCMOS18 [get_ports SMADC_1_RESET]
set_property IOSTANDARD LVCMOS18 [get_ports SMADC_1_CSA]
set_property IOSTANDARD LVCMOS18 [get_ports SMADC_1_PD]

##---------------------------------------------------------------------------
##ADC 1  (ADC 2)
##    INVERSION
##    76543210
##  A 11111010
##  B 11101110
##---------------------------------------------------------------------------
set_property PACKAGE_PIN AA4 [get_ports ADC_1_CLK_A_P]
set_property PACKAGE_PIN AA3 [get_ports ADC_1_FRAME_A_P]
set_property PACKAGE_PIN AD4 [get_ports {ADC_1_DATA_A_P[0]}]
set_property PACKAGE_PIN AC4 [get_ports {ADC_1_DATA_B_P[0]}]
set_property PACKAGE_PIN AB2 [get_ports {ADC_1_DATA_B_P[1]}]
set_property PACKAGE_PIN AB1 [get_ports {ADC_1_DATA_A_P[1]}]
set_property PACKAGE_PIN Y3 [get_ports {ADC_1_DATA_A_P[2]}]
set_property PACKAGE_PIN W1 [get_ports {ADC_1_DATA_B_P[2]}]
set_property PACKAGE_PIN V2 [get_ports {ADC_1_DATA_A_P[3]}]
set_property PACKAGE_PIN U2 [get_ports {ADC_1_DATA_B_P[3]}]
set_property PACKAGE_PIN AD1 [get_ports {ADC_1_DATA_A_P[4]}]
set_property PACKAGE_PIN AE3 [get_ports {ADC_1_DATA_B_P[4]}]
set_property PACKAGE_PIN Y6 [get_ports {ADC_1_DATA_A_P[5]}]
set_property PACKAGE_PIN AA5 [get_ports {ADC_1_DATA_B_P[5]}]
set_property PACKAGE_PIN U7 [get_ports {ADC_1_DATA_A_P[6]}]
set_property PACKAGE_PIN W6 [get_ports {ADC_1_DATA_B_P[6]}]
set_property PACKAGE_PIN AB6 [get_ports {ADC_1_DATA_A_P[7]}]
set_property PACKAGE_PIN U6 [get_ports {ADC_1_DATA_B_P[7]}]
set_property DIFF_TERM TRUE [get_ports ADC_1_CLK_A_P]
set_property DIFF_TERM TRUE [get_ports ADC_1_CLK_A_N]
set_property DIFF_TERM TRUE [get_ports ADC_1_FRAME_A_P]
set_property DIFF_TERM TRUE [get_ports ADC_1_FRAME_A_N]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_A_P[0]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_A_N[0]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_A_P[1]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_A_N[1]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_B_P[0]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_B_N[0]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_B_P[1]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_B_N[1]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_B_P[2]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_B_N[2]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_B_P[3]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_B_N[3]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_A_P[2]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_A_N[2]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_A_P[3]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_A_N[3]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_A_P[4]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_A_N[4]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_A_P[5]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_A_N[5]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_B_P[4]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_B_N[4]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_B_P[5]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_B_N[5]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_B_P[6]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_B_N[6]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_B_P[7]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_B_N[7]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_A_P[6]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_A_N[6]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_A_P[7]}]
set_property DIFF_TERM TRUE [get_ports {ADC_1_DATA_A_N[7]}]
set_property IOSTANDARD LVDS [get_ports ADC_1_CLK_A_P]
set_property IOSTANDARD LVDS [get_ports ADC_1_FRAME_A_P]
set_property IOSTANDARD LVDS [get_ports ADC_1_FRAME_A_N]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_A_P[0]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_A_N[0]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_A_P[1]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_A_N[1]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_B_P[0]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_B_N[0]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_B_P[1]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_B_N[1]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_B_P[2]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_B_N[2]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_B_P[3]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_B_N[3]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_A_P[2]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_A_N[2]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_A_P[3]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_A_N[3]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_A_P[4]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_A_N[4]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_A_P[5]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_A_N[5]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_B_P[4]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_B_N[4]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_B_P[5]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_B_N[5]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_B_P[6]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_B_N[6]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_B_P[7]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_B_N[7]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_A_P[6]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_A_N[6]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_A_P[7]}]
set_property IOSTANDARD LVDS [get_ports {ADC_1_DATA_A_N[7]}]
set_property IODELAY_GROUP IODELAY_ADC1 [get_cells adcs/adc_interface1/ADC_DESER1/delayctrl]
set_property IODELAY_GROUP IODELAY_ADC1 [get_cells adcs/adc_interface1/ADC_DESER1/idelaye2_clk]
set_property IODELAY_GROUP IODELAY_ADC1 [get_cells {adcs/adc_interface1/ADC_DESER1/pins[1].idelaye2_bus}]
set_property IODELAY_GROUP IODELAY_ADC1 [get_cells {adcs/adc_interface1/ADC_DESER1/pins[2].idelaye2_bus}]
set_property IODELAY_GROUP IODELAY_ADC1 [get_cells {adcs/adc_interface1/ADC_DESER1/pins[3].idelaye2_bus}]
set_property IODELAY_GROUP IODELAY_ADC1 [get_cells {adcs/adc_interface1/ADC_DESER1/pins[4].idelaye2_bus}]
set_property IODELAY_GROUP IODELAY_ADC1 [get_cells {adcs/adc_interface1/ADC_DESER1/pins[5].idelaye2_bus}]
set_property IODELAY_GROUP IODELAY_ADC1 [get_cells {adcs/adc_interface1/ADC_DESER1/pins[6].idelaye2_bus}]
set_property IODELAY_GROUP IODELAY_ADC1 [get_cells {adcs/adc_interface1/ADC_DESER1/pins[7].idelaye2_bus}]
set_property IODELAY_GROUP IODELAY_ADC1 [get_cells {adcs/adc_interface1/ADC_DESER1/pins[8].idelaye2_bus}]
set_property IODELAY_GROUP IODELAY_ADC1 [get_cells {adcs/adc_interface1/ADC_DESER1/pins[9].idelaye2_bus}]
set_property IODELAY_GROUP IODELAY_ADC1 [get_cells {adcs/adc_interface1/ADC_DESER1/pins[10].idelaye2_bus}]
set_property IODELAY_GROUP IODELAY_ADC1 [get_cells {adcs/adc_interface1/ADC_DESER1/pins[11].idelaye2_bus}]
set_property IODELAY_GROUP IODELAY_ADC1 [get_cells {adcs/adc_interface1/ADC_DESER1/pins[12].idelaye2_bus}]
set_property IODELAY_GROUP IODELAY_ADC1 [get_cells {adcs/adc_interface1/ADC_DESER1/pins[13].idelaye2_bus}]
set_property IODELAY_GROUP IODELAY_ADC1 [get_cells {adcs/adc_interface1/ADC_DESER1/pins[14].idelaye2_bus}]
set_property IODELAY_GROUP IODELAY_ADC1 [get_cells {adcs/adc_interface1/ADC_DESER1/pins[15].idelaye2_bus}]
set_property IODELAY_GROUP IODELAY_ADC1 [get_cells {adcs/adc_interface1/ADC_DESER1/pins[16].idelaye2_bus}]





set_property PACKAGE_PIN AB11 [get_ports clk_100]
create_clock -period 10.000 -name clk_100 -waveform {0.000 5.000} [get_ports clk_100]
set_property IOSTANDARD LVCMOS18 [get_ports clk_100]
set_property CLOCK_DEDICATED_ROUTE TRUE [get_nets clk_100]





#create_debug_core u_ila_0 ila
#set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
#set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
#set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
#set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
#set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
#set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
#set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
#set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
#set_property port_width 1 [get_debug_ports u_ila_0/clk]
#connect_debug_port u_ila_0/clk [get_nets [list adcs/adc_interface1/ADC_DESER1/clk_div_out]]
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
#set_property port_width 14 [get_debug_ports u_ila_0/probe0]
#connect_debug_port u_ila_0/probe0 [get_nets [list {adcs/adc_interface1/DATA_B_3[0]} {adcs/adc_interface1/DATA_B_3[1]} {adcs/adc_interface1/DATA_B_3[2]} {adcs/adc_interface1/DATA_B_3[3]} {adcs/adc_interface1/DATA_B_3[4]} {adcs/adc_interface1/DATA_B_3[5]} {adcs/adc_interface1/DATA_B_3[6]} {adcs/adc_interface1/DATA_B_3[7]} {adcs/adc_interface1/DATA_B_3[8]} {adcs/adc_interface1/DATA_B_3[9]} {adcs/adc_interface1/DATA_B_3[10]} {adcs/adc_interface1/DATA_B_3[11]} {adcs/adc_interface1/DATA_B_3[12]} {adcs/adc_interface1/DATA_B_3[13]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
#set_property port_width 14 [get_debug_ports u_ila_0/probe1]
#connect_debug_port u_ila_0/probe1 [get_nets [list {adcs/adc_interface1/DATA_B_7[0]} {adcs/adc_interface1/DATA_B_7[1]} {adcs/adc_interface1/DATA_B_7[2]} {adcs/adc_interface1/DATA_B_7[3]} {adcs/adc_interface1/DATA_B_7[4]} {adcs/adc_interface1/DATA_B_7[5]} {adcs/adc_interface1/DATA_B_7[6]} {adcs/adc_interface1/DATA_B_7[7]} {adcs/adc_interface1/DATA_B_7[8]} {adcs/adc_interface1/DATA_B_7[9]} {adcs/adc_interface1/DATA_B_7[10]} {adcs/adc_interface1/DATA_B_7[11]} {adcs/adc_interface1/DATA_B_7[12]} {adcs/adc_interface1/DATA_B_7[13]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
#set_property port_width 14 [get_debug_ports u_ila_0/probe2]
#connect_debug_port u_ila_0/probe2 [get_nets [list {adcs/adc_interface1/DATA_A_2[0]} {adcs/adc_interface1/DATA_A_2[1]} {adcs/adc_interface1/DATA_A_2[2]} {adcs/adc_interface1/DATA_A_2[3]} {adcs/adc_interface1/DATA_A_2[4]} {adcs/adc_interface1/DATA_A_2[5]} {adcs/adc_interface1/DATA_A_2[6]} {adcs/adc_interface1/DATA_A_2[7]} {adcs/adc_interface1/DATA_A_2[8]} {adcs/adc_interface1/DATA_A_2[9]} {adcs/adc_interface1/DATA_A_2[10]} {adcs/adc_interface1/DATA_A_2[11]} {adcs/adc_interface1/DATA_A_2[12]} {adcs/adc_interface1/DATA_A_2[13]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
#set_property port_width 14 [get_debug_ports u_ila_0/probe3]
#connect_debug_port u_ila_0/probe3 [get_nets [list {adcs/adc_interface1/DATA_A_1[0]} {adcs/adc_interface1/DATA_A_1[1]} {adcs/adc_interface1/DATA_A_1[2]} {adcs/adc_interface1/DATA_A_1[3]} {adcs/adc_interface1/DATA_A_1[4]} {adcs/adc_interface1/DATA_A_1[5]} {adcs/adc_interface1/DATA_A_1[6]} {adcs/adc_interface1/DATA_A_1[7]} {adcs/adc_interface1/DATA_A_1[8]} {adcs/adc_interface1/DATA_A_1[9]} {adcs/adc_interface1/DATA_A_1[10]} {adcs/adc_interface1/DATA_A_1[11]} {adcs/adc_interface1/DATA_A_1[12]} {adcs/adc_interface1/DATA_A_1[13]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
#set_property port_width 14 [get_debug_ports u_ila_0/probe4]
#connect_debug_port u_ila_0/probe4 [get_nets [list {adcs/adc_interface1/DATA_B_2[0]} {adcs/adc_interface1/DATA_B_2[1]} {adcs/adc_interface1/DATA_B_2[2]} {adcs/adc_interface1/DATA_B_2[3]} {adcs/adc_interface1/DATA_B_2[4]} {adcs/adc_interface1/DATA_B_2[5]} {adcs/adc_interface1/DATA_B_2[6]} {adcs/adc_interface1/DATA_B_2[7]} {adcs/adc_interface1/DATA_B_2[8]} {adcs/adc_interface1/DATA_B_2[9]} {adcs/adc_interface1/DATA_B_2[10]} {adcs/adc_interface1/DATA_B_2[11]} {adcs/adc_interface1/DATA_B_2[12]} {adcs/adc_interface1/DATA_B_2[13]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
#set_property port_width 14 [get_debug_ports u_ila_0/probe5]
#connect_debug_port u_ila_0/probe5 [get_nets [list {adcs/adc_interface1/DATA_A_7[0]} {adcs/adc_interface1/DATA_A_7[1]} {adcs/adc_interface1/DATA_A_7[2]} {adcs/adc_interface1/DATA_A_7[3]} {adcs/adc_interface1/DATA_A_7[4]} {adcs/adc_interface1/DATA_A_7[5]} {adcs/adc_interface1/DATA_A_7[6]} {adcs/adc_interface1/DATA_A_7[7]} {adcs/adc_interface1/DATA_A_7[8]} {adcs/adc_interface1/DATA_A_7[9]} {adcs/adc_interface1/DATA_A_7[10]} {adcs/adc_interface1/DATA_A_7[11]} {adcs/adc_interface1/DATA_A_7[12]} {adcs/adc_interface1/DATA_A_7[13]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
#set_property port_width 14 [get_debug_ports u_ila_0/probe6]
#connect_debug_port u_ila_0/probe6 [get_nets [list {adcs/adc_interface1/DATA_A_3[0]} {adcs/adc_interface1/DATA_A_3[1]} {adcs/adc_interface1/DATA_A_3[2]} {adcs/adc_interface1/DATA_A_3[3]} {adcs/adc_interface1/DATA_A_3[4]} {adcs/adc_interface1/DATA_A_3[5]} {adcs/adc_interface1/DATA_A_3[6]} {adcs/adc_interface1/DATA_A_3[7]} {adcs/adc_interface1/DATA_A_3[8]} {adcs/adc_interface1/DATA_A_3[9]} {adcs/adc_interface1/DATA_A_3[10]} {adcs/adc_interface1/DATA_A_3[11]} {adcs/adc_interface1/DATA_A_3[12]} {adcs/adc_interface1/DATA_A_3[13]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
#set_property port_width 14 [get_debug_ports u_ila_0/probe7]
#connect_debug_port u_ila_0/probe7 [get_nets [list {adcs/adc_interface1/DATA_B_5[0]} {adcs/adc_interface1/DATA_B_5[1]} {adcs/adc_interface1/DATA_B_5[2]} {adcs/adc_interface1/DATA_B_5[3]} {adcs/adc_interface1/DATA_B_5[4]} {adcs/adc_interface1/DATA_B_5[5]} {adcs/adc_interface1/DATA_B_5[6]} {adcs/adc_interface1/DATA_B_5[7]} {adcs/adc_interface1/DATA_B_5[8]} {adcs/adc_interface1/DATA_B_5[9]} {adcs/adc_interface1/DATA_B_5[10]} {adcs/adc_interface1/DATA_B_5[11]} {adcs/adc_interface1/DATA_B_5[12]} {adcs/adc_interface1/DATA_B_5[13]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
#set_property port_width 14 [get_debug_ports u_ila_0/probe8]
#connect_debug_port u_ila_0/probe8 [get_nets [list {adcs/adc_interface1/DATA_B_4[0]} {adcs/adc_interface1/DATA_B_4[1]} {adcs/adc_interface1/DATA_B_4[2]} {adcs/adc_interface1/DATA_B_4[3]} {adcs/adc_interface1/DATA_B_4[4]} {adcs/adc_interface1/DATA_B_4[5]} {adcs/adc_interface1/DATA_B_4[6]} {adcs/adc_interface1/DATA_B_4[7]} {adcs/adc_interface1/DATA_B_4[8]} {adcs/adc_interface1/DATA_B_4[9]} {adcs/adc_interface1/DATA_B_4[10]} {adcs/adc_interface1/DATA_B_4[11]} {adcs/adc_interface1/DATA_B_4[12]} {adcs/adc_interface1/DATA_B_4[13]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
#set_property port_width 14 [get_debug_ports u_ila_0/probe9]
#connect_debug_port u_ila_0/probe9 [get_nets [list {adcs/adc_interface1/DATA_B_0[0]} {adcs/adc_interface1/DATA_B_0[1]} {adcs/adc_interface1/DATA_B_0[2]} {adcs/adc_interface1/DATA_B_0[3]} {adcs/adc_interface1/DATA_B_0[4]} {adcs/adc_interface1/DATA_B_0[5]} {adcs/adc_interface1/DATA_B_0[6]} {adcs/adc_interface1/DATA_B_0[7]} {adcs/adc_interface1/DATA_B_0[8]} {adcs/adc_interface1/DATA_B_0[9]} {adcs/adc_interface1/DATA_B_0[10]} {adcs/adc_interface1/DATA_B_0[11]} {adcs/adc_interface1/DATA_B_0[12]} {adcs/adc_interface1/DATA_B_0[13]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
#set_property port_width 14 [get_debug_ports u_ila_0/probe10]
#connect_debug_port u_ila_0/probe10 [get_nets [list {adcs/adc_interface1/DATA_B_1[0]} {adcs/adc_interface1/DATA_B_1[1]} {adcs/adc_interface1/DATA_B_1[2]} {adcs/adc_interface1/DATA_B_1[3]} {adcs/adc_interface1/DATA_B_1[4]} {adcs/adc_interface1/DATA_B_1[5]} {adcs/adc_interface1/DATA_B_1[6]} {adcs/adc_interface1/DATA_B_1[7]} {adcs/adc_interface1/DATA_B_1[8]} {adcs/adc_interface1/DATA_B_1[9]} {adcs/adc_interface1/DATA_B_1[10]} {adcs/adc_interface1/DATA_B_1[11]} {adcs/adc_interface1/DATA_B_1[12]} {adcs/adc_interface1/DATA_B_1[13]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
#set_property port_width 14 [get_debug_ports u_ila_0/probe11]
#connect_debug_port u_ila_0/probe11 [get_nets [list {adcs/adc_interface1/DATA_A_0[0]} {adcs/adc_interface1/DATA_A_0[1]} {adcs/adc_interface1/DATA_A_0[2]} {adcs/adc_interface1/DATA_A_0[3]} {adcs/adc_interface1/DATA_A_0[4]} {adcs/adc_interface1/DATA_A_0[5]} {adcs/adc_interface1/DATA_A_0[6]} {adcs/adc_interface1/DATA_A_0[7]} {adcs/adc_interface1/DATA_A_0[8]} {adcs/adc_interface1/DATA_A_0[9]} {adcs/adc_interface1/DATA_A_0[10]} {adcs/adc_interface1/DATA_A_0[11]} {adcs/adc_interface1/DATA_A_0[12]} {adcs/adc_interface1/DATA_A_0[13]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
#set_property port_width 14 [get_debug_ports u_ila_0/probe12]
#connect_debug_port u_ila_0/probe12 [get_nets [list {adcs/adc_interface1/DATA_A_5[0]} {adcs/adc_interface1/DATA_A_5[1]} {adcs/adc_interface1/DATA_A_5[2]} {adcs/adc_interface1/DATA_A_5[3]} {adcs/adc_interface1/DATA_A_5[4]} {adcs/adc_interface1/DATA_A_5[5]} {adcs/adc_interface1/DATA_A_5[6]} {adcs/adc_interface1/DATA_A_5[7]} {adcs/adc_interface1/DATA_A_5[8]} {adcs/adc_interface1/DATA_A_5[9]} {adcs/adc_interface1/DATA_A_5[10]} {adcs/adc_interface1/DATA_A_5[11]} {adcs/adc_interface1/DATA_A_5[12]} {adcs/adc_interface1/DATA_A_5[13]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
#set_property port_width 14 [get_debug_ports u_ila_0/probe13]
#connect_debug_port u_ila_0/probe13 [get_nets [list {adcs/adc_interface1/DATA_A_6[0]} {adcs/adc_interface1/DATA_A_6[1]} {adcs/adc_interface1/DATA_A_6[2]} {adcs/adc_interface1/DATA_A_6[3]} {adcs/adc_interface1/DATA_A_6[4]} {adcs/adc_interface1/DATA_A_6[5]} {adcs/adc_interface1/DATA_A_6[6]} {adcs/adc_interface1/DATA_A_6[7]} {adcs/adc_interface1/DATA_A_6[8]} {adcs/adc_interface1/DATA_A_6[9]} {adcs/adc_interface1/DATA_A_6[10]} {adcs/adc_interface1/DATA_A_6[11]} {adcs/adc_interface1/DATA_A_6[12]} {adcs/adc_interface1/DATA_A_6[13]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
#set_property port_width 14 [get_debug_ports u_ila_0/probe14]
#connect_debug_port u_ila_0/probe14 [get_nets [list {adcs/adc_interface1/DATA_A_4[0]} {adcs/adc_interface1/DATA_A_4[1]} {adcs/adc_interface1/DATA_A_4[2]} {adcs/adc_interface1/DATA_A_4[3]} {adcs/adc_interface1/DATA_A_4[4]} {adcs/adc_interface1/DATA_A_4[5]} {adcs/adc_interface1/DATA_A_4[6]} {adcs/adc_interface1/DATA_A_4[7]} {adcs/adc_interface1/DATA_A_4[8]} {adcs/adc_interface1/DATA_A_4[9]} {adcs/adc_interface1/DATA_A_4[10]} {adcs/adc_interface1/DATA_A_4[11]} {adcs/adc_interface1/DATA_A_4[12]} {adcs/adc_interface1/DATA_A_4[13]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
#set_property port_width 14 [get_debug_ports u_ila_0/probe15]
#connect_debug_port u_ila_0/probe15 [get_nets [list {adcs/adc_interface1/DATA_B_6[0]} {adcs/adc_interface1/DATA_B_6[1]} {adcs/adc_interface1/DATA_B_6[2]} {adcs/adc_interface1/DATA_B_6[3]} {adcs/adc_interface1/DATA_B_6[4]} {adcs/adc_interface1/DATA_B_6[5]} {adcs/adc_interface1/DATA_B_6[6]} {adcs/adc_interface1/DATA_B_6[7]} {adcs/adc_interface1/DATA_B_6[8]} {adcs/adc_interface1/DATA_B_6[9]} {adcs/adc_interface1/DATA_B_6[10]} {adcs/adc_interface1/DATA_B_6[11]} {adcs/adc_interface1/DATA_B_6[12]} {adcs/adc_interface1/DATA_B_6[13]}]]
#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_div_out]

set_property PACKAGE_PIN A24 [get_ports chrage_trig_b]
set_property IOSTANDARD LVCMOS25 [get_ports chrage_trig_b]
set_property PACKAGE_PIN L22 [get_ports chrage_trig_d]
set_property PACKAGE_PIN T25 [get_ports dig_probe_c]
set_property IOSTANDARD LVCMOS18 [get_ports dig_probe_c]
set_property IOSTANDARD LVCMOS18 [get_ports trigb_mux_c]
set_property PACKAGE_PIN B21 [get_ports chrage_trig_a]
set_property IOSTANDARD LVCMOS25 [get_ports chrage_trig_a]
set_property PACKAGE_PIN E23 [get_ports chrage_trig_c]
set_property IOSTANDARD LVCMOS25 [get_ports chrage_trig_c]
set_property IOSTANDARD LVCMOS25 [get_ports chrage_trig_d]
set_property PACKAGE_PIN J15 [get_ports trigb_mux_b]
set_property IOSTANDARD LVCMOS18 [get_ports trigb_mux_b]
set_property PACKAGE_PIN L20 [get_ports dig_probe_b]
set_property IOSTANDARD LVCMOS18 [get_ports dig_probe_b]
set_property PACKAGE_PIN V23 [get_ports trigb_mux_d]
set_property IOSTANDARD LVCMOS18 [get_ports trigb_mux_d]
set_property IOSTANDARD LVCMOS18 [get_ports trigb_mux_a]
set_property PACKAGE_PIN AE23 [get_ports dig_probe_d]
set_property IOSTANDARD LVCMOS18 [get_ports dig_probe_d]
set_property PACKAGE_PIN D14 [get_ports dig_probe_a]
set_property IOSTANDARD LVCMOS18 [get_ports dig_probe_a]
set_property PACKAGE_PIN J8 [get_ports trigb_mux_a]

set_property PACKAGE_PIN L19 [get_ports B_ANALOG_DIN]
set_property PACKAGE_PIN H17 [get_ports B_ANALOG_CLK]
set_property PACKAGE_PIN P16 [get_ports C_ANALOG_CLK]
set_property PACKAGE_PIN K25 [get_ports C_ANALOG_DIN]
set_property PACKAGE_PIN U25 [get_ports D_ANALOG_CLK]
set_property PACKAGE_PIN AF23 [get_ports D_ANALOG_DIN]
set_property IOSTANDARD LVCMOS18 [get_ports D_ANALOG_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports D_ANALOG_DIN]
set_property IOSTANDARD LVCMOS18 [get_ports C_ANALOG_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports C_ANALOG_DIN]
set_property IOSTANDARD LVCMOS18 [get_ports B_ANALOG_DIN]
set_property IOSTANDARD LVCMOS18 [get_ports B_ANALOG_CLK]


set_false_path -from [get_clocks clk_ftdi] -to [get_clocks D_LVDS_DCLK]

set_property PACKAGE_PIN N16 [get_ports {C_TRG[0]}]
set_property PACKAGE_PIN R17 [get_ports {C_TRG[1]}]
set_property PACKAGE_PIN U16 [get_ports {C_TRG[2]}]
set_property PACKAGE_PIN U20 [get_ports {C_TRG[3]}]
set_property PACKAGE_PIN N21 [get_ports {C_TRG[4]}]
set_property PACKAGE_PIN N23 [get_ports {C_TRG[5]}]
set_property PACKAGE_PIN T23 [get_ports {C_TRG[6]}]
set_property PACKAGE_PIN T18 [get_ports {C_TRG[7]}]
set_property PACKAGE_PIN T19 [get_ports {C_TRG[8]}]
set_property PACKAGE_PIN R26 [get_ports {C_TRG[9]}]
set_property PACKAGE_PIN N17 [get_ports {C_TRG[10]}]
set_property PACKAGE_PIN R16 [get_ports {C_TRG[11]}]
set_property PACKAGE_PIN T17 [get_ports {C_TRG[12]}]
set_property PACKAGE_PIN U19 [get_ports {C_TRG[13]}]
set_property PACKAGE_PIN M21 [get_ports {C_TRG[14]}]
set_property PACKAGE_PIN R21 [get_ports {C_TRG[15]}]
set_property PACKAGE_PIN N24 [get_ports {C_TRG[16]}]
set_property PACKAGE_PIN T22 [get_ports {C_TRG[17]}]
set_property PACKAGE_PIN K26 [get_ports {C_TRG[18]}]
set_property PACKAGE_PIN P26 [get_ports {C_TRG[19]}]
set_property PACKAGE_PIN R20 [get_ports {C_TRG[20]}]
set_property PACKAGE_PIN L24 [get_ports {C_TRG[21]}]
set_property PACKAGE_PIN M24 [get_ports {C_TRG[22]}]
set_property PACKAGE_PIN L25 [get_ports {C_TRG[23]}]
set_property PACKAGE_PIN P20 [get_ports {C_TRG[24]}]
set_property PACKAGE_PIN P18 [get_ports {C_TRG[25]}]
set_property PACKAGE_PIN P24 [get_ports {C_TRG[26]}]
set_property PACKAGE_PIN R18 [get_ports {C_TRG[27]}]
set_property PACKAGE_PIN T24 [get_ports {C_TRG[28]}]
set_property PACKAGE_PIN N26 [get_ports {C_TRG[29]}]
set_property PACKAGE_PIN R22 [get_ports {C_TRG[30]}]
set_property PACKAGE_PIN T20 [get_ports {C_TRG[31]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[31]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[30]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[29]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[28]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[27]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C_TRG[0]}]
set_property PACKAGE_PIN U21 [get_ports {D_TRG[0]}]
set_property PACKAGE_PIN W24 [get_ports {D_TRG[1]}]
set_property PACKAGE_PIN Y22 [get_ports {D_TRG[2]}]
set_property PACKAGE_PIN Y23 [get_ports {D_TRG[3]}]
set_property PACKAGE_PIN AB25 [get_ports {D_TRG[4]}]
set_property PACKAGE_PIN AC26 [get_ports {D_TRG[5]}]
set_property PACKAGE_PIN AB24 [get_ports {D_TRG[6]}]
set_property PACKAGE_PIN AF24 [get_ports {D_TRG[7]}]
set_property PACKAGE_PIN AE22 [get_ports {D_TRG[8]}]
set_property PACKAGE_PIN AF22 [get_ports {D_TRG[9]}]
set_property PACKAGE_PIN U24 [get_ports {D_TRG[10]}]
set_property PACKAGE_PIN V24 [get_ports {D_TRG[11]}]
set_property PACKAGE_PIN U26 [get_ports {D_TRG[12]}]
set_property PACKAGE_PIN AA22 [get_ports {D_TRG[13]}]
set_property PACKAGE_PIN AA25 [get_ports {D_TRG[14]}]
set_property PACKAGE_PIN W26 [get_ports {D_TRG[15]}]
set_property PACKAGE_PIN AC21 [get_ports {D_TRG[16]}]
set_property PACKAGE_PIN AC22 [get_ports {D_TRG[17]}]
set_property PACKAGE_PIN AD24 [get_ports {D_TRG[18]}]
set_property PACKAGE_PIN AE25 [get_ports {D_TRG[19]}]
set_property PACKAGE_PIN U22 [get_ports {D_TRG[20]}]
set_property PACKAGE_PIN V22 [get_ports {D_TRG[21]}]
set_property PACKAGE_PIN V21 [get_ports {D_TRG[22]}]
set_property PACKAGE_PIN W21 [get_ports {D_TRG[23]}]
set_property PACKAGE_PIN W20 [get_ports {D_TRG[24]}]
set_property PACKAGE_PIN Y21 [get_ports {D_TRG[25]}]
set_property PACKAGE_PIN AB21 [get_ports {D_TRG[26]}]
set_property PACKAGE_PIN AB22 [get_ports {D_TRG[27]}]
set_property PACKAGE_PIN AD23 [get_ports {D_TRG[28]}]
set_property PACKAGE_PIN AD25 [get_ports {D_TRG[29]}]
set_property PACKAGE_PIN Y20 [get_ports {D_TRG[30]}]
set_property PACKAGE_PIN V26 [get_ports {D_TRG[31]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[31]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[30]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[29]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[28]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[27]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_TRG[0]}]
set_property PACKAGE_PIN R23 [get_ports trigb_mux_c]

set_false_path -from [get_clocks -of_objects [get_pins adcs/adc_interface1/ADC_DESER1/clkout_buf_inst/O]] -to [get_clocks -of_objects [get_pins adcs/dcm_ref/inst/mmcm_adv_inst/CLKOUT2]]
set_false_path -from [get_clocks -of_objects [get_pins adcs/dcm_ref/inst/mmcm_adv_inst/CLKOUT2]] -to [get_clocks -of_objects [get_pins adcs/adc_interface1/ADC_DESER1/clkout_buf_inst/O]]
set_false_path -from [get_clocks D_LVDS_DCLK] -to [get_clocks -of_objects [get_pins adcs/adc_interface1/ADC_DESER1/clkout_buf_inst/O]]




set_property IODELAY_GROUP TIME_GROUP_ADC_1 [get_cells adcs/adc_interface1/ADC_DESER1/pins[0].idelaye2_bus]
set_false_path -from [get_clocks D_LVDS_DCLK] -to [get_clocks -of_objects [get_pins dcm_top/inst/mmcm_adv_inst/CLKOUT0]]


##---------------------------------------------------------------------------
## AUX PROPAGATION CLOCK 25MHz
##---------------------------------------------------------------------------

set_property PACKAGE_PIN AA10 [get_ports CLK_AUX_OUT_25]
set_property IOSTANDARD LVCMOS18 [get_ports CLK_AUX_OUT_25]

set_property PACKAGE_PIN C13 [get_ports UART_TTL_TX]
set_property IOSTANDARD LVCMOS18 [get_ports UART_TTL_TX]

set_property PACKAGE_PIN C14 [get_ports UART_TTL_RX]
set_property IOSTANDARD LVCMOS18 [get_ports UART_TTL_RX]

